version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      docker: 20
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 026090546401.dkr.ecr.us-east-1.amazonaws.com

  pre_build:
    commands:
      - echo Setting IMAGE_TAG...
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo IMAGE_TAG=$IMAGE_TAG
      - REPO_URI=026090546401.dkr.ecr.us-east-1.amazonaws.com/ecommerce-flask

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest

      - echo Writing image definitions to imagedefinitions.json...
      - printf '[{"name":"ecommerce","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yaml
    - k8s/*
